package Vista;

import Controlador.Controlador;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.border.Border;
import org.edisoncor.gui.panel.PanelAvatarChooser;
import java.awt.Dimension;
import static org.edisoncor.gui.util.BlendComposite.Color;
import java.awt.Color;
import javax.swing.JProgressBar;
import javax.swing.JSeparator;
/**
 *
 * @author Broker
 */

public class VentanaInicio extends javax.swing.JFrame {

    Border loweredbevel = BorderFactory.createLoweredBevelBorder();
    Controlador cont = new Controlador();
       
  

    public VentanaInicio() {

        initComponents();
    
    }
                            
    public void mostrarTareas(int numero_tareas, Object[][] tareas) {
        panel.removeAll();
        
        Dimension dimensionTarea = new Dimension();
        Dimension dimensionProgreso = new Dimension();
        dimensionProgreso.setSize(200,25);
        dimensionTarea.setSize(300, 200);
        Color c=new Color(200, 100,50);
        Color rojo = new Color(	252,40,30);
        Color verde = new Color(118,255,122);
        Color naranja = new Color(255,182,83);
        
        text = new JTextPane[numero_tareas];
        
        barra = new JProgressBar[numero_tareas];
 
        if(numero_tareas<3){
            panel.setLayout(new GridLayout(3, 1));
        }else  panel.setLayout(new GridLayout(numero_tareas, 1));
       
        for (int i = 0; i < text.length; i++) {
            text[i] = new JTextPane();
            barra[i] = new JProgressBar();
            panel.add(text[i]);
            text[i].setOpaque(true);
            barra[i].setSize(dimensionProgreso);
            barra[i].setLocation(300, 150);
            text[i].setMaximumSize(dimensionTarea);
            text[i].setSize(dimensionTarea);
            text[i].setEditable(false);
            text[i].setFocusable(true);
            text[i].setName((String)tareas[i][0]);       
            text[i].setBorder(loweredbevel);
            text[i].setContentType("text/html");
            text[i].add(barra[i]);
            int progreso=Integer.parseInt((String) tareas[i][5]);
            barra[i].setString(progreso+"%");
            barra[i].setValue(progreso);
            barra[i].setStringPainted(true);
            if(progreso>=0 & progreso<=25)  {
                barra[i].setForeground(rojo);}
            
            if(progreso>25 & progreso<=75) { 
                barra[i].setForeground(naranja);}

             if(progreso>75 & progreso<=100) { 
                 barra[i].setForeground(verde); }
            barra[i].setVisible(true);
            text[i].setText(
                    
                    ""
                            + "<!DOCTYPE html>\n" +
"\n" +
"<html >\n" +
"<head>"
                            + "<style>"
                            + "p:hover{\n" +
"	background-color:yellow;" +
"}"
 + "body:hover{"
                            + "background-color:#FFFFFF; text-decoration:underline; font-weight:bold"
  + "}\n" +
"h1\n" +
"{\n" +
"color:orange;\n" +
"text-align:center;\n" +
"}\n" +
"p\n" +
                            
"{\n" +
"font-family:\"Times New Roman\";\n" +
"font-size:20px;\n" +
"}</style> </head><body>"
                            + "<span style=\"color: red; font-size: 25px\">•</span>"
                            + "  <h1>"+tareas[i][1]+"</h1>"+
                    "<h2>"+tareas[i][2]+"</h2>"+
                    "<p>Descripción: "+tareas[i][3]+"</p>"+
                    "Prioridad: <h3>"+tareas[i][4]+"</h3>"
                     +"Fecha: "+tareas[i][6]       
+"</body></html>"
                    );
            
           
           
            
        }

       

        setVisible(true);
        //mostrarTareas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        panel1 = new org.edisoncor.gui.panel.Panel();
        iniciarSesion = new javax.swing.JButton();
        nuevaTarea = new javax.swing.JButton();
        conectado = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new org.edisoncor.gui.panel.Panel();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ordenar = new javax.swing.JComboBox();
        filtrar = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Tareas");

        desktop.setBackground(new java.awt.Color(255, 255, 255));
        desktop.setMaximumSize(new java.awt.Dimension(999999999, 999999999));

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestortareas/Imagenes/fondo.jpg"))); // NOI18N

        iniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestortareas/Imagenes/1400377276_User.png"))); // NOI18N
        iniciarSesion.setText("Iniciar Sesion");
        iniciarSesion.setToolTipText("Inicia sesion con tu usuario");
        iniciarSesion.setBorder(null);
        iniciarSesion.setBorderPainted(false);
        iniciarSesion.setContentAreaFilled(false);
        iniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iniciarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        nuevaTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestortareas/Imagenes/add.png"))); // NOI18N
        nuevaTarea.setText("Nueva Tarea");
        nuevaTarea.setToolTipText("Añande nuevas tareas.");
        nuevaTarea.setBorder(null);
        nuevaTarea.setBorderPainted(false);
        nuevaTarea.setContentAreaFilled(false);
        nuevaTarea.setFocusPainted(false);
        nuevaTarea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevaTarea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        conectado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestortareas/Imagenes/1400394282_accept-database.png"))); // NOI18N
        conectado.setBorder(null);
        conectado.setBorderPainted(false);
        conectado.setContentAreaFilled(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(500, 500));

        panel.setToolTipText("Linea de Tiempo");
        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestortareas/Imagenes/fondo.jpg"))); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel);

        actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestortareas/Imagenes/Synchronize.png"))); // NOI18N
        actualizar.setText("Actualizar");
        actualizar.setToolTipText("Actualiza la linea de tiempo de tareas.");
        actualizar.setBorder(null);
        actualizar.setBorderPainted(false);
        actualizar.setContentAreaFilled(false);
        actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        actualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestortareas/Imagenes/minus.png"))); // NOI18N
        eliminar.setText("Eliminar Tarea");
        eliminar.setToolTipText("Elimina Tareas.");
        eliminar.setBorder(null);
        eliminar.setBorderPainted(false);
        eliminar.setContentAreaFilled(false);
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setText("Ordenar por:");

        ordenar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige", "fecha", "progreso" }));

        filtrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestortareas/Imagenes/buscar por usuario.png"))); // NOI18N
        filtrar.setText("Filtrar usuario");
        filtrar.setToolTipText("");
        filtrar.setBorderPainted(false);
        filtrar.setContentAreaFilled(false);
        filtrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        filtrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filtrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestortareas/Imagenes/cerrar sesion.png"))); // NOI18N
        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.setToolTipText("Cierra la sesion del usuario activo");
        cerrarSesion.setBorderPainted(false);
        cerrarSesion.setContentAreaFilled(false);
        cerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(nuevaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(filtrar)
                .addGap(45, 45, 45)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addGap(33, 33, 33))
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(conectado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(actualizar)
                            .addComponent(filtrar))
                        .addGap(34, 34, 34))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(iniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nuevaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(conectado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktop.setLayer(panel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizar;
    public javax.swing.JButton cerrarSesion;
    public javax.swing.JButton conectado;
    public javax.swing.JDesktopPane desktop;
    public javax.swing.JButton eliminar;
    public javax.swing.JButton filtrar;
    public javax.swing.JButton iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JButton nuevaTarea;
    public javax.swing.JComboBox ordenar;
    public org.edisoncor.gui.panel.Panel panel;
    public org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
    public JTextPane text[];
    public JScrollPane scrollPane;
    public JProgressBar barra[];

}
